-- JobSift PostgreSQL schema v1.
-- Timestamps and JSON remain TEXT in this first migration so existing
-- deterministic comparisons, hashing, and serialization remain unchanged.

CREATE TABLE IF NOT EXISTS jobsift_schema_metadata (
  singleton BOOLEAN PRIMARY KEY DEFAULT TRUE CHECK(singleton),
  schema_version TEXT NOT NULL,
  installed_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS jobs (
  id TEXT PRIMARY KEY,
  source TEXT NOT NULL,
  source_job_id TEXT NOT NULL,
  source_board_id TEXT NOT NULL,
  canonical_url TEXT NOT NULL,
  content_fingerprint TEXT NOT NULL,
  first_seen_at TEXT NOT NULL,
  last_seen_at TEXT NOT NULL,
  last_verified_at TEXT NOT NULL,
  lifecycle TEXT NOT NULL,
  payload_json TEXT NOT NULL,
  UNIQUE(source, source_board_id, source_job_id)
);
CREATE INDEX IF NOT EXISTS ix_jobs_canonical_url ON jobs(canonical_url);

CREATE TABLE IF NOT EXISTS job_matches (
  job_id TEXT NOT NULL REFERENCES jobs(id),
  client_id TEXT NOT NULL,
  decision TEXT NOT NULL,
  score INTEGER,
  matched_reasons_json TEXT NOT NULL,
  rejection_reasons_json TEXT NOT NULL,
  evaluated_at TEXT NOT NULL,
  matcher_version TEXT NOT NULL,
  PRIMARY KEY(job_id, client_id)
);

CREATE TABLE IF NOT EXISTS scoped_job_matches (
  job_id TEXT NOT NULL REFERENCES jobs(id),
  client_id TEXT NOT NULL,
  match_scope_id TEXT NOT NULL,
  decision TEXT NOT NULL,
  score INTEGER,
  matched_reasons_json TEXT NOT NULL,
  rejection_reasons_json TEXT NOT NULL,
  evaluated_at TEXT NOT NULL,
  matcher_version TEXT NOT NULL,
  PRIMARY KEY(job_id, client_id, match_scope_id)
);
CREATE INDEX IF NOT EXISTS ix_scoped_job_matches_client_scope
  ON scoped_job_matches(client_id, match_scope_id, job_id);

CREATE TABLE IF NOT EXISTS collection_runs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source TEXT NOT NULL,
  target TEXT NOT NULL,
  started_at TEXT NOT NULL,
  completed_at TEXT,
  status TEXT NOT NULL,
  metrics_json TEXT NOT NULL,
  errors_json TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS exports (
  job_id TEXT NOT NULL REFERENCES jobs(id),
  client_id TEXT NOT NULL,
  destination TEXT NOT NULL,
  exported_at TEXT NOT NULL,
  PRIMARY KEY(job_id, client_id, destination)
);

CREATE TABLE IF NOT EXISTS delivery_groups (
  id TEXT PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS posting_delivery_groups (
  job_id TEXT PRIMARY KEY REFERENCES jobs(id),
  group_id TEXT NOT NULL REFERENCES delivery_groups(id)
);
CREATE INDEX IF NOT EXISTS ix_posting_group ON posting_delivery_groups(group_id);

CREATE TABLE IF NOT EXISTS delivery_keys (
  job_id TEXT NOT NULL REFERENCES jobs(id),
  kind TEXT NOT NULL,
  value TEXT NOT NULL,
  PRIMARY KEY(job_id, kind, value)
);
CREATE INDEX IF NOT EXISTS ix_delivery_key ON delivery_keys(kind, value);

CREATE TABLE IF NOT EXISTS job_identity_ledger (
  source TEXT NOT NULL,
  source_board_id TEXT NOT NULL,
  source_job_id TEXT NOT NULL,
  canonical_url TEXT NOT NULL,
  employer_id TEXT,
  company TEXT NOT NULL,
  first_seen_at TEXT NOT NULL,
  last_seen_at TEXT NOT NULL,
  pruned_at TEXT NOT NULL,
  was_delivered INTEGER NOT NULL CHECK(was_delivered IN (0,1)),
  PRIMARY KEY(source, source_board_id, source_job_id)
);

CREATE TABLE IF NOT EXISTS job_retention_evidence (
  job_id TEXT PRIMARY KEY REFERENCES jobs(id) ON DELETE CASCADE,
  posted_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS group_deliveries (
  group_id TEXT NOT NULL REFERENCES delivery_groups(id),
  client_id TEXT NOT NULL,
  destination TEXT NOT NULL,
  job_id TEXT NOT NULL REFERENCES jobs(id),
  exported_at TEXT NOT NULL,
  PRIMARY KEY(group_id, client_id, destination)
);

CREATE TABLE IF NOT EXISTS historical_imports (
  id TEXT PRIMARY KEY,
  client_id TEXT NOT NULL,
  workbook_sha256 TEXT NOT NULL,
  imported_at TEXT NOT NULL,
  importer_version TEXT NOT NULL,
  row_count INTEGER NOT NULL,
  UNIQUE(client_id, workbook_sha256)
);

CREATE TABLE IF NOT EXISTS historical_job_links (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  import_id TEXT NOT NULL REFERENCES historical_imports(id),
  client_id TEXT NOT NULL,
  original_url TEXT NOT NULL,
  normalized_url TEXT NOT NULL,
  source TEXT,
  source_board_id TEXT,
  source_job_id TEXT,
  title TEXT NOT NULL,
  company TEXT NOT NULL,
  operator_status TEXT NOT NULL CHECK(operator_status IN ('applied','not_applied','unknown')),
  source_sheet TEXT NOT NULL,
  source_row INTEGER NOT NULL,
  imported_at TEXT NOT NULL,
  UNIQUE(import_id, source_sheet, source_row, original_url)
);
CREATE INDEX IF NOT EXISTS ix_historical_url
  ON historical_job_links(client_id, normalized_url);
CREATE INDEX IF NOT EXISTS ix_historical_identity
  ON historical_job_links(client_id, source, source_board_id, source_job_id);

CREATE TABLE IF NOT EXISTS destination_observed_links (
  client_id TEXT NOT NULL,
  destination TEXT NOT NULL,
  normalized_url TEXT NOT NULL,
  source TEXT,
  source_board_id TEXT,
  source_job_id TEXT,
  first_observed_at TEXT NOT NULL,
  PRIMARY KEY(client_id, destination, normalized_url)
);
CREATE INDEX IF NOT EXISTS ix_destination_observed_url
  ON destination_observed_links(client_id, normalized_url);
CREATE INDEX IF NOT EXISTS ix_destination_observed_identity
  ON destination_observed_links(client_id, source, source_board_id, source_job_id);

CREATE TABLE IF NOT EXISTS historical_blacklist_evidence (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  import_id TEXT NOT NULL REFERENCES historical_imports(id),
  client_id TEXT NOT NULL,
  value TEXT NOT NULL,
  kind TEXT NOT NULL CHECK(kind IN ('company','note')),
  source_sheet TEXT NOT NULL,
  source_row INTEGER NOT NULL,
  imported_at TEXT NOT NULL,
  UNIQUE(import_id, source_sheet, source_row, value)
);
CREATE INDEX IF NOT EXISTS ix_historical_blacklist_client
  ON historical_blacklist_evidence(client_id);

CREATE TABLE IF NOT EXISTS inventory_runs (
  run_id TEXT PRIMARY KEY,
  plan_id TEXT NOT NULL,
  started_at TEXT NOT NULL,
  completed_at TEXT,
  status TEXT NOT NULL CHECK(status IN ('running','success','partial','failure'))
);
CREATE INDEX IF NOT EXISTS ix_inventory_runs_plan_started
  ON inventory_runs(plan_id, started_at);

CREATE TABLE IF NOT EXISTS inventory_run_jobs (
  run_id TEXT NOT NULL REFERENCES inventory_runs(run_id) ON DELETE CASCADE,
  job_id TEXT NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,
  target_identity TEXT NOT NULL,
  PRIMARY KEY(run_id, job_id, target_identity)
);
CREATE INDEX IF NOT EXISTS ix_inventory_run_jobs_run
  ON inventory_run_jobs(run_id, job_id);

CREATE TABLE IF NOT EXISTS inventory_target_observations (
  run_id TEXT NOT NULL REFERENCES inventory_runs(run_id) ON DELETE CASCADE,
  target_identity TEXT NOT NULL,
  source TEXT NOT NULL,
  started_at TEXT NOT NULL,
  completed_at TEXT NOT NULL,
  status TEXT NOT NULL,
  runtime_ms INTEGER NOT NULL CHECK(runtime_ms >= 0),
  raw_postings_received INTEGER NOT NULL CHECK(raw_postings_received >= 0),
  normalized_jobs INTEGER NOT NULL CHECK(normalized_jobs >= 0),
  postings_with_trustworthy_timestamps INTEGER NOT NULL
    CHECK(postings_with_trustworthy_timestamps >= 0),
  postings_at_most_24h_old INTEGER NOT NULL
    CHECK(postings_at_most_24h_old >= 0),
  PRIMARY KEY(run_id, target_identity)
);
CREATE INDEX IF NOT EXISTS ix_inventory_target_observations_target_completed
  ON inventory_target_observations(target_identity, completed_at);
CREATE INDEX IF NOT EXISTS ix_inventory_target_observations_source_completed
  ON inventory_target_observations(source, completed_at);

CREATE TABLE IF NOT EXISTS inventory_target_coverage_state (
  target_identity TEXT PRIMARY KEY,
  source TEXT NOT NULL,
  first_observed_at TEXT NOT NULL,
  previous_observed_at TEXT,
  last_observed_at TEXT NOT NULL,
  observation_count INTEGER NOT NULL CHECK(observation_count >= 1),
  last_run_id TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_inventory_target_coverage_state_source_last
  ON inventory_target_coverage_state(source, last_observed_at);

CREATE TABLE IF NOT EXISTS inventory_refresh_schedule_state (
  schedule_key TEXT PRIMARY KEY,
  last_completed_cohort INTEGER NOT NULL CHECK(last_completed_cohort >= -1),
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS source_discovery_targets (
  target_identity TEXT PRIMARY KEY,
  source TEXT NOT NULL,
  coordinates_json TEXT NOT NULL,
  company_hint TEXT NOT NULL,
  first_discovered_at TEXT NOT NULL,
  last_discovered_at TEXT NOT NULL,
  last_discovery_source TEXT NOT NULL,
  last_discovery_crawl_id TEXT NOT NULL,
  last_discovery_url TEXT NOT NULL,
  latest_health_classification TEXT,
  latest_health_checked_at TEXT,
  latest_health_evidence_sha256 TEXT,
  health_current_postings INTEGER,
  health_inventory_exact INTEGER
    CHECK(health_inventory_exact IN (0,1) OR health_inventory_exact IS NULL),
  health_error TEXT,
  admitted INTEGER NOT NULL DEFAULT 0 CHECK(admitted IN (0,1)),
  admitted_at TEXT,
  next_health_check_at TEXT
);
CREATE INDEX IF NOT EXISTS ix_source_discovery_targets_health_due
  ON source_discovery_targets(next_health_check_at, latest_health_checked_at);
CREATE INDEX IF NOT EXISTS ix_source_discovery_targets_admitted
  ON source_discovery_targets(admitted, latest_health_checked_at);

CREATE TABLE IF NOT EXISTS source_discovery_evidence (
  evidence_id TEXT PRIMARY KEY,
  target_identity TEXT NOT NULL
    REFERENCES source_discovery_targets(target_identity) ON DELETE CASCADE,
  discovery_source TEXT NOT NULL,
  crawl_id TEXT NOT NULL,
  query_id TEXT NOT NULL,
  captured_at TEXT NOT NULL,
  discovered_url TEXT NOT NULL,
  observed_at TEXT NOT NULL,
  evidence_sha256 TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_source_discovery_evidence_target
  ON source_discovery_evidence(target_identity, observed_at);

CREATE TABLE IF NOT EXISTS source_discovery_health_evidence (
  evidence_id TEXT PRIMARY KEY,
  target_identity TEXT NOT NULL
    REFERENCES source_discovery_targets(target_identity) ON DELETE CASCADE,
  checked_at TEXT NOT NULL,
  classification TEXT NOT NULL,
  current_postings INTEGER,
  inventory_exact INTEGER CHECK(inventory_exact IN (0,1) OR inventory_exact IS NULL),
  http_status INTEGER,
  request_count INTEGER NOT NULL,
  error TEXT,
  evidence_json TEXT NOT NULL,
  evidence_sha256 TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_source_discovery_health_target
  ON source_discovery_health_evidence(target_identity, checked_at);

CREATE TABLE IF NOT EXISTS source_discovery_cursors (
  discovery_source TEXT NOT NULL,
  query_id TEXT NOT NULL,
  crawl_id TEXT NOT NULL,
  page INTEGER NOT NULL CHECK(page >= 0),
  pages INTEGER NOT NULL CHECK(pages >= 1),
  updated_at TEXT NOT NULL,
  PRIMARY KEY(discovery_source, query_id)
);

CREATE TABLE IF NOT EXISTS daily_batches (
  batch_id TEXT PRIMARY KEY,
  generation_id TEXT,
  client_id TEXT NOT NULL,
  destination TEXT NOT NULL,
  idempotency_key TEXT NOT NULL,
  requested_quota INTEGER NOT NULL CHECK(requested_quota > 0),
  selected_count INTEGER NOT NULL CHECK(selected_count >= 0 AND selected_count <= requested_quota),
  shortfall INTEGER NOT NULL CHECK(shortfall = requested_quota - selected_count),
  status TEXT NOT NULL CHECK(status IN ('prepared','failed','delivered')),
  assembled_at TEXT NOT NULL,
  delivered_at TEXT,
  request_json TEXT NOT NULL,
  counts_json TEXT NOT NULL,
  dedupe_version TEXT NOT NULL,
  export_before_sha256 TEXT,
  export_after_sha256 TEXT,
  error TEXT,
  UNIQUE(client_id, destination, idempotency_key)
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_pending_batch_destination
  ON daily_batches(destination)
  WHERE export_after_sha256 IS NOT NULL AND status != 'delivered';

CREATE TABLE IF NOT EXISTS daily_batch_items (
  batch_id TEXT NOT NULL REFERENCES daily_batches(batch_id),
  ordinal INTEGER NOT NULL CHECK(ordinal > 0),
  delivery_group_id TEXT NOT NULL,
  representative_job_id TEXT NOT NULL REFERENCES jobs(id),
  evidence_sha256 TEXT NOT NULL,
  matcher_version TEXT NOT NULL,
  export_row_json TEXT NOT NULL,
  PRIMARY KEY(batch_id, ordinal),
  UNIQUE(batch_id, delivery_group_id)
);

CREATE TABLE IF NOT EXISTS daily_batch_candidates (
  batch_id TEXT NOT NULL REFERENCES daily_batches(batch_id),
  job_id TEXT NOT NULL REFERENCES jobs(id),
  delivery_group_id TEXT NOT NULL,
  evidence_sha256 TEXT NOT NULL,
  decision TEXT NOT NULL,
  disposition TEXT NOT NULL,
  PRIMARY KEY(batch_id, job_id)
);

CREATE TABLE IF NOT EXISTS client_sheet_destinations (
  client_id TEXT NOT NULL,
  destination_id TEXT NOT NULL,
  display_name TEXT NOT NULL,
  spreadsheet_id TEXT NOT NULL,
  sheet_id INTEGER NOT NULL,
  tab_name TEXT NOT NULL,
  header_json TEXT NOT NULL,
  header_sha256 TEXT NOT NULL,
  column_mapping_json TEXT NOT NULL,
  config_sha256 TEXT NOT NULL,
  status TEXT NOT NULL CHECK(status IN ('ready','disabled')),
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  PRIMARY KEY(client_id, destination_id)
);
CREATE INDEX IF NOT EXISTS ix_client_sheet_destinations_client
  ON client_sheet_destinations(client_id, status, destination_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_client_sheet_physical_worksheet
  ON client_sheet_destinations(spreadsheet_id, sheet_id);

CREATE TABLE IF NOT EXISTS client_delivery_profiles (
  client_id TEXT NOT NULL,
  destination_id TEXT NOT NULL,
  sourcing_plan_id TEXT NOT NULL,
  daily_quota INTEGER NOT NULL CHECK(daily_quota >= 1 AND daily_quota <= 5000),
  status TEXT NOT NULL CHECK(status IN ('active','paused')),
  delivery_mode TEXT NOT NULL CHECK(delivery_mode IN ('review','auto')),
  timezone TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  PRIMARY KEY(client_id, destination_id)
);
CREATE INDEX IF NOT EXISTS ix_client_delivery_profiles_status
  ON client_delivery_profiles(status, client_id, destination_id);

CREATE TABLE IF NOT EXISTS operator_outcome_events (
  event_id TEXT PRIMARY KEY,
  client_id TEXT NOT NULL,
  subject_type TEXT NOT NULL CHECK(subject_type IN ('posting','history_entry')),
  subject_id TEXT NOT NULL,
  value TEXT NOT NULL CHECK(value IN ('applied','not_applied')),
  version INTEGER NOT NULL CHECK(version > 0),
  actor_type TEXT NOT NULL,
  actor_id TEXT NOT NULL,
  recorded_at TEXT NOT NULL,
  action TEXT NOT NULL,
  idempotency_key TEXT NOT NULL,
  request_sha256 TEXT NOT NULL,
  source_reference TEXT NOT NULL,
  result_json TEXT NOT NULL,
  UNIQUE(client_id, subject_type, subject_id, version),
  UNIQUE(actor_type, actor_id, client_id, action, idempotency_key)
);

CREATE TABLE IF NOT EXISTS operator_outcome_imports (
  import_record_id TEXT PRIMARY KEY,
  actor_type TEXT NOT NULL,
  actor_id TEXT NOT NULL,
  client_id TEXT NOT NULL,
  source_reference TEXT NOT NULL,
  external_record_id TEXT NOT NULL,
  request_sha256 TEXT NOT NULL,
  record_json TEXT NOT NULL,
  recorded_at TEXT NOT NULL,
  event_id TEXT REFERENCES operator_outcome_events(event_id),
  result_json TEXT NOT NULL,
  UNIQUE(actor_type, actor_id, client_id, source_reference, external_record_id)
);

CREATE OR REPLACE FUNCTION jobsift_reject_operator_state_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS 'BEGIN
  RAISE EXCEPTION ''operator outcome state is immutable'';
END';

DROP TRIGGER IF EXISTS outcome_events_no_update ON operator_outcome_events;
CREATE TRIGGER outcome_events_no_update
BEFORE UPDATE ON operator_outcome_events
FOR EACH ROW EXECUTE FUNCTION jobsift_reject_operator_state_mutation();

DROP TRIGGER IF EXISTS outcome_events_no_delete ON operator_outcome_events;
CREATE TRIGGER outcome_events_no_delete
BEFORE DELETE ON operator_outcome_events
FOR EACH ROW EXECUTE FUNCTION jobsift_reject_operator_state_mutation();

DROP TRIGGER IF EXISTS outcome_imports_no_update ON operator_outcome_imports;
CREATE TRIGGER outcome_imports_no_update
BEFORE UPDATE ON operator_outcome_imports
FOR EACH ROW EXECUTE FUNCTION jobsift_reject_operator_state_mutation();

DROP TRIGGER IF EXISTS outcome_imports_no_delete ON operator_outcome_imports;
CREATE TRIGGER outcome_imports_no_delete
BEFORE DELETE ON operator_outcome_imports
FOR EACH ROW EXECUTE FUNCTION jobsift_reject_operator_state_mutation();

INSERT INTO jobsift_schema_metadata(singleton, schema_version, installed_at)
VALUES (TRUE, 'postgres-v1', CURRENT_TIMESTAMP::text)
ON CONFLICT (singleton) DO NOTHING;
